axf/axf/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('contents.urls',namespace='contents')),
    url(r'^',include('market.urls',namespace='market')),
    url(r'^',include('carts.urls',namespace='carts')),
    url(r'^',include('orders.urls',namespace='orders')),
    url(r'^',include('users.urls',namespace='users')),
]

axf/carts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^cart/$',views.index,name='index'),
    url(r'^selects/$',views.selects,name='selects')
]

axf/market/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^market/(\d+)/(\d+)/(\d+)/$',views.index,name='index'),
    url(r'^savadata/$',views.savadata,name='savadata')
]

axf/orders/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^orders/$',views.index,name='index'),
    url(r'^not_pay/$',views.not_pay,name='not_pay'),
    url(r'^order_pay/(\d+)/$',views.order_pay,name='order_pay')
]

axf/users/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login/$',views.login,name='login'),
    url(r'^register/$',views.register,name='register'),
    url(r'^sendsms/$',views.sendsms,name='sendsms'),
    url(r'^info/$',views.info,name='info'),
    url(r'^logout/$',views.logout,name='logout'),
    url(r'^email/$',views.email,name='email'),
    url(r'^active/$',views.active,name='active')
]

axf/market/models.py
from django.db import models

# Create your models here.

# typeid
# typename
# childtypenames
# typesort

#商品分类模型
class FoodType(models.Model):
    typeid = models.IntegerField(verbose_name='商品分类ID')
    typename = models.CharField(max_length=32,verbose_name='商品分类名称')
    childtypenames = models.CharField(max_length=255,verbose_name='子分类名称')
    typesort = models.IntegerField(verbose_name='排序')

    class Meta:
        db_table = 'axf_foodtype'

#商品模型
class Goods(models.Model):
    productid = models.IntegerField(verbose_name='商品ID')
    productimg = models.CharField(max_length=255,verbose_name='商品图片信息')
    productname = models.CharField(max_length=128,verbose_name='商品名称')
    productlongname = models.CharField(max_length=255,verbose_name='商品详细名称')
    specifics = models.CharField(max_length=64,verbose_name='商品规格')
    price = models.DecimalField(max_digits=6,decimal_places=2,verbose_name='商品价格')
    marketprice = models.DecimalField(max_digits=6,decimal_places=2,verbose_name='商品市场价格')
    categoryid = models.IntegerField(verbose_name='所属分类ID')
    childcid = models.IntegerField(verbose_name='所属子分类ID')
    childcidname = models.CharField(max_length=128,verbose_name='商品子分类名称')
    storenums = models.IntegerField(verbose_name='商品库存')
    productnum = models.IntegerField(verbose_name='商品销量')

    class Meta:
        db_table = 'axf_goods'

axf/carts/views.py
import json

from django.http import HttpResponse
from django.shortcuts import render
from django_redis import get_redis_connection

# Create your views here.
from market.models import Goods


def index(request):
    if request.session.get('username'):
        username = request.session.get('username')
        redis_cli = get_redis_connection('cart')
        data = redis_cli.get(f'cart_{username}')
    else:
        #取出cookie中的数据
        data = request.COOKIES.get('cookie_data')

    #初始化总价
    totalprice = 0
    #判断cookie是否有数据
    data_list = []
    if data:
        data = json.loads(data)
        for d in data:
            goods = Goods.objects.get(id=d)
            data_dict = {
                'id' : goods.id,
                'img' : goods.productimg,
                'name' : goods.productlongname,
                'price' : goods.price,
                'num' : data[d]['count'],
                'selected' : data[d]['selected']
            }

            data_list.append(data_dict)

            if data[d]['selected'] == '1':
                totalprice += goods.price*int(data[d]['count'])

    context = {
        'data_list' : data_list,
        'totalprice' : totalprice
    }
    return render(request,'cart.html',context)


def selects(request):
    #获取selects的值
    selected = request.POST.get('selected')
    if request.session.get('username'):
        username = request.session.get('username')
        redis_cli = get_redis_connection('cart')
        cookie_data = redis_cli.get(f'cart_{username}')

    else:
        #获取cookie_data值
        cookie_data = request.COOKIES.get('cookie_data')

    #将cookie_data转为字典形式
    cookie_data = json.loads(cookie_data)

    for data in cookie_data:
        cookie_data[data]['selected'] = selected

    #将cookie_data转为json字符串
    cookie_data = json.dumps(cookie_data)

    #重设cookie_data
    res = HttpResponse({'data':'ok'})

    if request.session.get('username'):
        redis_cli.set(f'cart_{username}',cookie_data)
    else:
        res.set_cookie('cookie_data',cookie_data)

    return res

axf/market/views.py
import json

from django.http import HttpResponse, JsonResponse
from django.shortcuts import render

# Create your views here.
from market.models import FoodType, Goods
from django_redis import get_redis_connection


def index(request,typeid,twoid,sortid):
    #取出分类信息
    foodtype = FoodType.objects.order_by('typesort')

    if typeid == '0':
        #默认取出热销榜的数据
        #取出热销榜的分类ID
        cid = foodtype[0].typeid
        #获取热销榜的子分类名称
        childcate = foodtype[0].childtypenames
    else:
        cid = typeid
        #获取对应的大分类的子分类名称
        childdate = FoodType.objects.get(typeid = cid)
        childcate = childdate.childtypenames
    # print(childcate)
    #找出typeid对应的goods
    goods = Goods.objects.filter(categoryid = cid)

    if twoid != '0':
        goods = goods.filter(childcid = twoid)


    #全部分类: 0  # 进口水果:103534#国产水果:103533
    #将子分类名称转换为字典格式 {'0':'全部分类','103534':'进口水果','103533':'国产水果'}
    childcateDict = {}
    childcateList = childcate.split('#')
    for one in childcateList:
        childcateList2 = one.split(':')
        childcateDict[childcateList2[1]] = childcateList2[0]
    # print(childcateDict)

    twoName = childcateDict[twoid]

    #根据价格和销量排序
    order_data = [
        ['综合排序','0'],
        ['价格升序','1','price'],
        ['价格降序','2','-price'],
        ['销量升序','3','productnum'],
        ['销量降序','4','-productnum'],
    ]

    if sortid!='0':
        goods = goods.order_by(order_data[int(sortid)][2])

    sortName = order_data[int(sortid)][0]


    context = {
        'foodtype' : foodtype,
        'goods' : goods,
        'cid' : int(cid),
        'childcateDict' : childcateDict,
        'twoid' : twoid,
        'twoName' : twoName,
        'order_data' : order_data,
        'sortid' : sortid,
        'sortName' : sortName
    }

    return render(request,'market.html',context)


def savadata(request):

    #接受数据
    gid = request.POST.get('gid')
    count = request.POST.get('count')
    selected = request.POST.get('selected','1')#默认选中
    # print(gid,count,selected)


    #判断用户是否登录
    if request.session.get('username'):
        username = request.session.get('username')

        #取出redis中购物车数据
        redis_cli = get_redis_connection('cart')
        cookie_data = redis_cli.get(f'cart_{username}')

    else:
        #判断cookie中数据，有数据相同需要覆盖，没有需要新增
        cookie_data = request.COOKIES.get('cookie_data')


    if cookie_data:
        # 存在cookie
        cookie_data = json.loads(cookie_data)
        cookie_data[gid] = {'count':count,'selected':selected}
    else:
        #不存在则新增
        #将数据保存在cookie中
        #{'gid':{'count':'数量','selected':'选中状态'}}
        cookie_data = {gid:{'count':count,'selected':selected}}

    #如果商品数量为0,则删除该商品
    if count=='0':
        del cookie_data[gid]

    #将cookie_data转为json字符串
    cookie_data = json.dumps(cookie_data)
    res = JsonResponse({'data':'ok'})

    if request.session.get('username'):
        #用户登录状态，设置session，将商品数据存在redis中
        redis_cli.set(f'cart_{username}',cookie_data)
    else:
        #用户未登录，设置cookie
        res.set_cookie('cookie_data',cookie_data)
    return res

axf/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title></title>

    <link rel="stylesheet" href="/static/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/swiper.css">
    <link rel="stylesheet" href="/static/css/reset.css">
    <link rel="stylesheet" href="/static/axf/main/css/main.css">
    <script type="text/javascript" src="/static/js/jquery.js"></script>
    <script type="text/javascript" src="/static/js/bootstrap.js"></script>
    <script type="text/javascript" src="/static/js/base.js"></script>



    {% block jscss %}

    {% endblock %}

</head>


<body>

<header></header>

{% block main %}

{% endblock %}


<footer>
    <a href="{% url 'contents:index' %}" class="home">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>首页</dd>
        </dl>
    </a>
    <a href="{% url 'market:index' 0 0 0 %}" class="market">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>闪购</dd>
        </dl>
    </a>
    <a href="{% url 'carts:index' %}" class="cart">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>购物车</dd>
        </dl>
    </a>
    <a href="{% url 'users:info' %}" class="mine_icon">
        <dl>
            <dt>
                <span></span>
            </dt>
            <dd>我的</dd>
        </dl>
    </a>
</footer>





</body>
</html>

axf/templates/cart.html
{% extends 'base.html' %}


{% block jscss %}

    <link rel="stylesheet" href="/static/axf/main/css/cart.css">


{% endblock %}

{% block main %}

<div id="cart">
    <h3>Cart</h3>
    <div class="full">
        <section>
            <ul>
                <li>收&nbsp;&nbsp;货&nbsp;&nbsp;人:&nbsp;Rock</li>
                <li>电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话:&nbsp;110</li>
                <li>地&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;址:&nbsp;宝盛里</li>
            </ul>

            <div class="bill">

                <p>闪送超市</p>
                <p>0元起送满30免运费22:00前可送达</p>
                <a href="#">凑单专区</a>

            </div>

            <div class="delivery">
                <span>收货时间</span>
                <span>一小时内送达</span>
                <a href="#">可预订&gt;</a>
            </div>

            <div class="delivery">
                <span>收获备注</span>
                <input type="text" placeholder="可输入100字以内的特殊要求">
            </div>

            <ul>
                {% for data in data_list %}


                <li class="menuList" cartid="{{ data.id }}">
                    <div class="confirm">

                        {% if data.selected == '1' %}
                            <input type="checkbox" checked class="select_check" goodsid="{{ data.id }}"/>
                        {% else %}
                            <input type="checkbox" class="select_check" goodsid="{{ data.id }}"/>
                        {% endif %}

                    </div>

                    <a href="#">
                        <img src="{{ data.img }}" alt="">
                        <p>{{ data.name }}</p>
                        <p class="">¥<span class="cartPrice">{{ data.price }}</span></p>
                    </a>

                    <section>
                        <button class="subShopping" goodsid="{{ data.id }}">-</button>
                        <span class="cartCount">{{ data.num }}</span>
                        <button class="addShopping" goodsid="{{ data.id }}">+</button>
                    </section>

                </li>
                {% endfor %}



            </ul>

            <div class="payTheBill">
                <div class="all_select">
                    <input type="checkbox" checked class="select_all_check"/>
                </div>

                <p>
                    <span>全选</span>
                    <span>共计:</span>
                    <span id="total_price">{{ totalprice }}</span>
                </p>

                <span id="make_order"><a href="{% url 'orders:index' %}" id="add_order">下单</a></span>
            </div>

        </section>


    </div>
</div>
    <script>

{#    页面刷新时判断选中栏状态#}
    show_all_selected();
    function cacl() {
    {#    遍历所有商品#}
        var totalprice = 0;

        {#设置标志位，判断$('.menuList').each()是否为空，避免购物车商品全部移除时总价不清零#}
        var flag = 0;
        $('.menuList').each(function () {
        {#    筛选出选中的商品#}
            flag = 1;
            if($(this).find('.select_check').prop('checked')){
                var price = parseFloat($(this).find('.cartPrice').text());
                var num = parseInt($(this).find('.cartCount').text());
                {#计算总价#}
                totalprice += price*num
            }
        {#    将totalprice赋值给总价#}
            $('#total_price').text(totalprice.toFixed(2));
        });
        if(flag === 0){
            $('#total_price').text(0);
        }
    }

    function show_all_selected(){
        var flag = true;
        $('.select_check').each(function () {

            if (!$(this).prop('checked')) {
                flag = false;
                return false;
            }
        });
        if(flag){
            $('.select_all_check').prop('checked',true)
        }else{
            $('.select_all_check').prop('checked',false)
        }
    }

    $(function(){
        {#商品增加的点击事件#}
        $(".addShopping").click(function () {
            {#找到商品数量#}
            var num = parseInt($(this).siblings("span").text());
            {#console.log(typeof num);#}
            num += 1;
            $(this).siblings("span").text(num);


            {#获取商品id和数量#}
            var gid = $(this).attr("goodsid");
            var count = num;

            {#计算总价#}
            cacl();

            $.ajax({
                url:{% url 'market:savadata' %},
                type:'post',
                data:{
                    "gid" : gid,
                    "count" : count
                },
                dataType : 'json',
                headers : {'X-CSRFToken':'{{  csrf_token  }}'},
                success : function (data) {

                }
            })
        });

        {#商品减少的点击事件#}
        $(".subShopping").click(function () {
            {#找到商品数量#}
            var num = parseInt($(this).siblings("span").text());
            {#console.log(typeof num);#}

            num -= 1;

            {#判断商品数量，如果为零，将其移除#}
            if (num == 0){
                $(this).parent().parent().remove();
                show_all_selected();
            }


            $(this).siblings("span").text(num);

            {#获取商品id和数量#}
            var gid = $(this).attr("goodsid");
            var count = num;

            {#计算总价#}
            cacl();

            $.ajax({
                url:'{% url "market:savadata" %}',
                type:'post',
                data:{
                    "gid" : gid,
                    "count" : count
                },
                dataType : 'json',
                headers : {'X-CSRFToken':'{{  csrf_token  }}'},
                success : function (data) {

                }
            })
        });

        $('.select_check').click(function () {
            {# 将商品id和选中状态以及数量传递给后端 #}
            var gid = $(this).attr('goodsid');
            var count = $(this).parent().parent().find('.cartCount').text();
            var selected = $(this).prop('checked') ? '1' : '0';

            {#计算总价#}
            cacl();
            {#判断全选状态栏状态#}
            show_all_selected();

            $.ajax({
                url : '{% url "market:savadata" %}',
                type : 'post',
                dataType : 'json',
                headers : {'X-CSRFToken':"{{ csrf_token }}"},
                data : {
                    'gid' : gid,
                    'count' : count,
                    'selected' : selected
                },
                success : function (data) {
                    
                }
            })

        });



        $('.select_all_check').click(function () {
            {#同步全选框和所有子选框#}
            $('.select_check').prop('checked',$(this).prop('checked'));

            var selected = $(this).prop('checked') ? '1' : '0';

            {#计算总价#}
            cacl();
             {#同步cookie中的selected状态#}
            $.ajax({
                url : '{% url "carts:selects" %}',
                type : 'post',
                dataType : 'json',
                headers : {'X-CSRFToken':"{{ csrf_token }}"},
                data : {
                    'selected' : selected
                },
                success : function (data) {

                }
            })
        });

        {#判断购物车物品是否为全部未选中状态，若为全部未选中，则禁止跳转#}
        $('#add_order').click(function () {
            var flag = true;
            $('.select_check').each(function () {

                if ($(this).prop('checked')) {
                    flag = false;
                    return true;
                }
            });
            if(flag){
                return false;
            }
        });

    });

    </script>
{% endblock %}

axf/templates/email.html
{% extends 'base.html' %}


{% block jscss %}


    <link rel="stylesheet" href="/static/axf/user/css/user.css">
{% endblock %}


{% block main %}


<div class="container" style="padding-top: 70px">
    <form method="post" action="">

        {% csrf_token %}

        <p></p>

            {% if user.email == '' %}

            <div class="form-group">
                <label for="username_input">email</label>
                <input name="email" type="text" class="form-control" id="email" placeholder="邮箱">
            </div>
            <input type="hidden" name="type" value="1">
            <button type="submit" class="btn btn-success btn-block">保存</button>

            {% elif user.is_active == 0 %}
            <div class="form-group">
                <label for="username_input">email</label>
                <input name="email_active" type="text" class="form-control" id="email" value="{{ user.email }}"/>
            </div>
            <input type="hidden" name="type" value="2">
            <button type="submit" class="btn btn-success btn-block">请点击激活</button>

            {% else %}
            <div class="form-group">
                <label for="username_input">email</label>
                <input name="email" type="text" class="form-control" id="email" value="{{ user.email }}"/>
            </div>
            <button class="btn btn-success btn-block" disabled>已激活</button>


            {% endif %}



    </form>
</div>
{% endblock %}

axf/templates/login.html
{% extends 'base.html' %}


{% block jscss %}

    <script type="text/javascript" src="/static/js/md5.js"></script>

    <link rel="stylesheet" href="/static/axf/user/css/user.css">

    <script type="text/javascript" src="/static/axf/user/js/login.js"></script>


{% endblock %}

{% block main %}


<div class="container" style="padding-top: 70px">
    <form method="post" action="">

        {% csrf_token %}

        <p></p>

        <div class="form-group">
            <label for="username_input">用户名</label>
            <input name="username" type="text" class="form-control" id="username_input" placeholder="用户名/邮箱">
        </div>

        <div class="form-group">
            <label for="password_input">密码</label>
            <input name="password" type="password" class="form-control" id="password_input" placeholder="请输入密码">
        </div>


        <button type="submit" class="btn btn-success btn-block">登录</button>
        <button class="btn btn-success btn-block"><a href="{% url 'users:register' %}" style='color: #ffffff'>注册</a></button>
    </form>


</div>

{% endblock %}

axf/templates/market.html
{% extends 'base.html' %}

    {% block jscss %}

    <link rel="stylesheet" href="/static/axf/main/css/market.css">

    <script type="text/javascript" src="/static/js/swiper.jquery.js"></script>
    <script type="text/javascript" src="/static/axf/main/js/market.js"></script>

    {% endblock %}


{% block main %}

<div id="market">

    <aside>
        <ul>
            {% for ft in foodtype %}
            <li>
                <a href="{% url 'market:index' ft.typeid 0 0 %}">{{ ft.typename }}</a>
                {% if cid == ft.typeid %}
                    <span class="yellowSlide"></span>
                {% endif %}

            </li>
            {% endfor %}



        </ul>
    </aside>


    <section>
        <nav>
            <ul>
                <li id="all_types"><span>{{ twoName }} <span class="glyphicon glyphicon-chevron-down"></span></span></li>
                <li id="sort_rule"><span>{{ sortName }} <span class="glyphicon glyphicon-chevron-down"></span></span></li>
            </ul>
        </nav>

        <menu>
            <ul>
                {% for good in goods %}

                <li>
                    <a href="#">
                        <img src="{{ good.productimg }}" alt=''>
                        <div class="shoppingInfo">
                            <h6>{{ good.productlongname }}</h6>
                            <p class="detailTag">
                            </p>
                            <p class="unit">{{ good.specifics }}</p>
                            <p class="price">
                                <span>{{ good.price }}</span>
                                <s>{{ good.marketprice }}</s>
                            </p>
                        </div>
                    </a>

                    <section>
                        <button goodsid="{{ good.id }}" class="subShopping">－</button>
                        <span>0</span>
                        <button goodsid="{{ good.id }}" class="addShopping">＋</button>
                    </section>
                </li>
                {% endfor %}


            </ul>
            <div id="all_types_container">
                <div>
                    {% for k,v in childcateDict.items %}
                    <a href="{% url 'market:index' cid k 0 %}">
                        {% if twoid == k %}
                            <button class="btn btn-success">{{ v }}</button>
                        {% else %}
                            <button class="btn btn-default">{{ v }}</button>
                        {% endif %}

                    </a>
                    {% endfor %}


                </div>
            </div>

            <div id="sort_rule_container">
                <div>

                    {% for orders in order_data %}

                    <a href="{% url 'market:index' cid twoid orders.1 %}">
                    {% if sortid == orders.1 %}
                        <button class="btn btn-success">{{ orders.0 }}</button>
                    {% else %}
                        <button class="btn btn-default">{{ orders.0 }}</button>
                    {% endif %}
                    </a>

                    {% endfor %}



                </div>
            </div>
        </menu>

    </section>


</div>

    <script>
    $(function(){
        {#商品增加的点击事件#}
        $(".addShopping").click(function () {
            {#找到商品数量#}
            var num = parseInt($(this).siblings("span").text());
            {#console.log(typeof num);#}
            num += 1;
            $(this).siblings("span").text(num);


            {#获取商品id和数量#}
            var gid = $(this).attr("goodsid");
            var count = num;

            $.ajax({
                url:{% url 'market:savadata' %},
                type:'post',
                data:{
                    "gid" : gid,
                    "count" : count
                },
                dataType : 'json',
                headers : {'X-CSRFToken':'{{  csrf_token  }}'},
                success : function (data) {

                }
            })
        });

        {#商品减少的点击事件#}
        $(".subShopping").click(function () {
            {#找到商品数量#}
            var num = parseInt($(this).siblings("span").text());
            {#console.log(typeof num);#}
            if (num == 0){
                return
            }
            num -= 1;
            $(this).siblings("span").text(num);

            {#获取商品id和数量#}
            var gid = $(this).attr("goodsid");
            var count = num;

            $.ajax({
                url:{% url 'market:savadata' %},
                type:'post',
                data:{
                    "gid" : gid,
                    "count" : count
                },
                dataType : 'json',
                headers : {'X-CSRFToken':'{{  csrf_token  }}'},
                success : function (data) {

                }
            })
        })
    })
    
    </script>

{% endblock %}

{#当点击+号时，需要将数量加一，并将商品id，数量，默认选中状态保存在cookie中#}

axf/templates/mine.html
{% extends 'base.html' %}

{% block jscss %}


    <link rel="stylesheet" href="/static/axf/main/css/mine.css">

{% endblock %}


{% block main %}


    <div id="mine">
        <div class="fixed">
            {% if login %}
                <span>
                    <img class="u_icon" src="{{ jpg_show }}" alt="">
                </span>
                    <p>{{ user.username }}</p>
            {% else %}
                    <span class="glyphicon glyphicon-user"></span>
                    <p id="not_login"><a href="{% url 'users:login' %}">未登录</a></p>
            {% endif %}

            <p>
                <span class="glyphicon glyphicon-fire"></span>
                <span>等级</span>
            </p>

                {% if not login %}

                <div id="regis"><a href="{% url 'users:register' %}">注册</a></div>

                {% endif %}

            <p>
                <span class="glyphicon glyphicon-heart"></span>
                <span>商品收藏</span>
            </p>

        </div>

        <div class="mine">
            <p>
                <span>全部订单</span>
                <a href="#">全部订单></a>
            </p>

            <nav id="nav">
                <ul>
                    <li id="not_pay">
                        {% if login %}
                            <span class="badge">
{#                                {{ no_pay_count }}#}
                                {{ no_pay }}

                            </span>
                        {% endif %}
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-usd"></span>
                            </dt>
                            {% if login %}
                                <dd><a href="{% url 'orders:not_pay' %}">待付款</a></dd>
                            {% else %}
                                <dd>待付款</dd>
                            {% endif %}
                        </dl>
                    </li>
                    <li>
                        {% if login %}
                            <span class="badge">
{#                                {{ no_receive_count }}#}
                                {{ no_receive }}
                            </span>

                        {% endif %}

                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            <dd>待收货</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-pencil"></span>
                            </dt>
                            <dd>待评价</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-retweet"></span>
                            </dt>
                            <dd>退款/售后</dd>
                        </dl>
                    </li>
                </ul>
            </nav>
            <menu>
                <ul>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-envelope"></span>
                            </dt>
                            {% if login %}
                                <dd><a href="{% url 'users:email' %}">我的邮箱</a></dd>
                            {% else %}
                                <dd>我的邮箱</dd>
                            {% endif %}

                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-credit-card"></span>
                            </dt>
                            <dd>优惠卷</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-import"></span>
                            </dt>
                            <dd>收货地址</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-phone-alt"></span>
                            </dt>
                            <dd>客服反馈</dd>
                        </dl>
                    </li>
                    <li>
                        <dl>
                            <dt>
                                <span class="glyphicon glyphicon-asterisk"></span>
                            </dt>
                            <dd>关于我们</dd>
                        </dl>
                    </li>
                </ul>
            </menu>

                <p>
                    <a href="{% url 'users:logout' %}">退出</a>
                </p>


        </div>

    </div>
{% endblock %}

axf/templates/order_list_not_pay.html
{% extends 'base.html' %}

{% block jscss %}

    <link rel="stylesheet" href="/static/axf/order/css/order.css">
    <link rel="stylesheet" href="/static/axf/order/css/order_list_not_pay.css">

{% endblock %}

{% block main %}


<div id="order_list_not_pay" class="container" style="padding-top: 70px">

    <ol>

        {% for order_code,data_dict in data_dicts.items %}

        <li>
            <ul class="order" orderid="1111">
                <h6><a href="{% url 'orders:order_pay' order_code %}">订单编号:{{ order_code }}</a></h6>

                {% for data in data_dict %}

                <li class="menuList">
                    <a href="#">
                        <img src="{{ data.img }}" alt="">
                        <p>{{ data.name }}</p>
                        <p class="presentPrice">{{ data.price }}</p>
                    </a>


                    <section>
                        <span>{{ data.count }}</span>
                    </section>

                </li>

                {% endfor %}

            </ul>

        </li>

        {% endfor %}


    </ol>


</div>

{% endblock %}